### ISSUE TITLE
Item detection

### ISSUE THREAD

**Issue by ghost** [konserwa1992/roseBot#2]
Heyy, 
Thanks for the amazing work on this. 
I noticed an issue with the pick-up function. It looks like there is an issue with determining the items around a player. 
DataReader#GetItemsAroundPlayer
In case a monster drops multiple items at once, only one of the items being dropped has an index in the range of 0 to 0xFFFF. Therefore, only one item will be detected if a multi drop occurs. 
If the item that was detected is being picked up, one of the next items of the multidrop appears at the index of the previous item -1.
Example: 3 items drop at once from one monster. 1 item is detected from the bot at e.g. index 1000. If you pick up this item, one of the other two will appear at index 999, and if that one is picked up the last one appears at index 998. 
I haven't figured out yet where the game stores the other items until the first item is being picked up. Is it possible that one ItemPointer can contain multiple items?

**Comment by konserwa1992** [comment]
Sorry, i didnt notice this post.

I didn't check exactly how its work, to be honest i dont quite sure if 0xFFFF is fine. I decided to choose this value because they multiply table by 2(short). 
Also if monster drop 2 items bot will pickup them(mostly) so i didn't bother.

**Comment by konserwa1992** [comment]
![obraz](https://github.com/konserwa1992/roseBot/assets/38973532/2d6d7bef-a40b-4636-989e-a2272cdd6105)

**Comment by konserwa1992** [comment]
public List<IObject> GetItemsAroundPlayerV2()
        {
            List<IObject> itemList = new List<IObject>();

            Process _proc = Process.GetCurrentProcess();

            long* RDI = (long*)(*(long*)(_proc.MainModule.BaseAddress.ToInt64() + 0x14C1520));
            long* RBX = (long*)((long)RDI + 0x2a0b8);

            RBX = (long*)*RBX; //select first item from list

            while ((long)RBX != 0x0)
            {
                long* itemAddr = (long*)*(long*)((long)RDI + ((*(short*)RBX) * 8) + 0x22080);
                Item nearItem = new Item(0, itemAddr);
                itemList.Add(nearItem);
                RBX = (long*)*((long*)((long)RBX+0x8));
            }

            return itemList;
        }

**Comment by konserwa1992** [comment]
new picking 
![obraz](https://github.com/konserwa1992/roseBot/assets/38973532/dd7c3383-a8c8-4609-8387-5d3ae3e0ba65)
